### ISSUE TITLE
Spørgsmål

### ISSUE THREAD

**Issue by rhgiter** [Sdahl1234/Sunseeker-lawn-mower#1]
Hej,

Det hele ser ud til at fungere perfekt :-).  på nær lige 'multi zone auto' hvad er den til ? når jeg slå den til ,så bliver den automatisk slået fra efter nogle sekunder. (jeg kan dog heller ikke finde funktioen i appen)

Er det muligt at slå tidsstyringen fra/til

Er det muligt at få Ugeplan over i HA's kalender?

ved du om firmware bliver opdateret automatisk (automatisk er slå til i appen) - hvis man sletter den originale app?

Mange tak for integrationen.

**Comment by Sdahl1234** [comment]
Jeg har ikke lige haft tid til at teste så meget efter den er kommet på græs.
Har du prøvet at slå multizone fra og bagefter slå multi zone auto til. Jeg tror/håber at multi zone auto selv finder ud af at starte forskellige steder, mens multizone bruger de 4 valgte procenter.

Med hensyn til at slå tidstyrring fra så skal man sætte dagene til 00:00 - 00:00. 
Jeg har overvejet at lave en switch til at slå den fra, altså sætte alle dage til 00:00 - 00:00, men mangler et sted at gemme oplysningerne om hvad den var når den skal slås til igen. Eneste løsning jeg kan komme på er at gemme det i en fil i config.

Det er muligt at får ugeplanen i HA's kalender. Jeg har noteret det på min liste.

Firmware bliver IKKE opdateret hvis du sletter appen.

**Comment by rhgiter** [comment]
Tak for dit svar

multizone virker,  men ikke multi zone auto, selv om jeg slå multizone til/fra - multi zone auto slukker igen efter 2 sekunder.

jeg det ville være rart at man nemt kan slukke for tidsstyring, hvis det bliver varmt og tørt på et tidspunkt, så man ikke skal programmere den om, det kan måske "bare" være en automation som selv udfylder felterne tid/trim - fx. så når automatioen/helper er slået fra så udfylder den selv med 00:00  

klip kant knappen virker ikke  hos mig.

**Comment by Sdahl1234** [comment]
@rhgiter 
Jeg kunne også selv godt bruge at kunne slå tidsstyrring fra, så det ser jeg lige på.
Jeg tester lige klip kant hos mig når vejret tillader det
